apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: book-app
spec:
  template:
    spec:
      containers:
        - name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
