apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowPrivilegedContainers
metadata:
  name: disallow-privileged-containers
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet", "ReplicaSet"]
    namespaces:
      - book-app
    excludedNamespaces:
      - kube-system
  parameters:
    exemptImages: []
