apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: book-app-gateway
  namespace: book-app
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "book-app.example.com"
        - "*.book-app.example.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: book-app-tls
      hosts:
        - "book-app.example.com"
