# Jaeger Helm values
# helm install jaeger jaegertracing/jaeger \
#   -n book-observability --create-namespace -f values.yaml

provisionDataStore:
  cassandra: false

allInOne:
  enabled: true
  replicas: 1
  image:
    tag: latest
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  extraEnv:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"

storage:
  type: memory

collector:
  enabled: false

query:
  enabled: false

agent:
  enabled: false
