apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-frontend.yaml
  - deployment-api-gateway.yaml
  - deployment-product-service.yaml
  - deployment-order-service.yaml
  - deployment-postgres.yaml
  - service-frontend.yaml
  - service-api-gateway.yaml
  - service-product-service.yaml
  - service-order-service.yaml
  - service-postgres.yaml
  - ingress.yaml
